run:
  timeout: 3m
  tests: false

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - forcetypeassert
    - fatcontext
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - predeclared
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unused
    - wastedassign
    - whitespace
  disable:
    # Should be readded in the future with a dedicated PR to do the fix
    - funlen
    - gocognit
    - gofumpt
    - nestif
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - unconvert
    - unparam

    # Disabled with a reason
    - canonicalheader # Clickhouse uses non-canonical header
    - depguard # Way too spammy and forces whitelist of all imports
    - gochecknoglobals # incompatible with the way we define our flags currently
    - noctx # disabled because we do not plan to distribute this code as a library
    - prealloc # we are not after some perf
    - tagliatelle # disabled because we are dependant on external API that do not follow the right naming
linters-settings:
  gosec:
    excludes:
      - G115 # Unsafe cast of ints. Needs to be looked at by a dedicated PR
