run:
  timeout: 3m
  tests: false

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosimple
    - importas
    - makezero
    - misspell
    - nakedret
    - predeclared
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unused
    - varcheck
    - whitespace
  disable:
    # Should be readded in the future with a dedicated PR to do the fix
    - cyclop
    - exhaustive
    - forcetypeassert
    - funlen
    - gocognit
    - gofumpt
    - gosec
    - govet
    - ifshort
    - ineffassign
    - nestif
    - nilerr
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - wastedassign

    # Disabled with a reason
    - gochecknoglobals # incompatible with the way we define our flags currently
    - maligned # checker not supported anymore
    - noctx # disabled because we do not plan to distribute this code as a library
    - prealloc # we are not after some perf
    - tagliatelle # disabled because we are dependant on external API that do not follow the right naming
