---
builds:
  - id: linux-amd64
    binary: chproxy
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - "-tags={{ .Env.BUILD_TAG }}"
    ldflags:
      - -s
      - -w
      - -X main.buildTime={{ .Date }}
      - -X main.buildRevision={{ .FullCommit }}
      - -X main.buildTag={{ .Version }}
    gcflags:
      - -trimpath={{.Env.GOPATH}}/src

  - id: linux-arm64
    binary: chproxy-arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - "-tags={{ .Env.BUILD_TAG }}"
    ldflags:
      - -s
      - -w
      - -X main.buildTime={{ .Date }}
      - -X main.buildRevision={{ .FullCommit }}
      - -X main.buildTag={{ .Version }}
    gcflags:
      - -trimpath={{.Env.GOPATH}}/src

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "contentsquareplatform/chproxy:{{ .Version }}"

snapshot:
  name_template: "{{ .FullCommit }}-SNAPSHOT"

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  github:
    owner: ContentSquare
    name: chproxy

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false
