---
before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: chproxy
    binary: chproxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - "-tags={{ .Env.BUILD_TAG }}"
    ldflags:
      - -s
      - -w
      - -X main.buildTime={{ .Date }}
      - -X main.buildRevision={{ .FullCommit }}
      - -X main.buildTag={{ .Version }}
    gcflags:
      - -trimpath={{.Env.GOPATH}}/src

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "contentsquareplatform/chproxy:{{ .Version }}"
      - "contentsquareplatform/chproxy:{{ .Version }}-amd64"
    build_flag_templates:
      - "--build-arg=BINARY=chproxy"
  - goos: linux
    goarch: arm64
    image_templates:
      - "contentsquareplatform/chproxy:{{ .Version }}-arm64"
    build_flag_templates:
      - "--build-arg=BINARY=chproxy"
      - "--platform=linux/arm64"
  - goos: linux
    goarch: arm64
    image_templates:
      - "contentsquareplatform/chproxy:{{ .Version }}-arm64v8"
    build_flag_templates:
      - "--build-arg=BINARY=chproxy"
      - "--platform=linux/arm64/v8"

snapshot:
  name_template: "{{ .FullCommit }}-SNAPSHOT"

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  github:
    owner: ContentSquare
    name: chproxy

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false
