ARG GO_VER=1.21.2
FROM golang:${GO_VER}-alpine AS build

RUN apk add --no-cache --update zstd-static zstd-dev make gcc musl-dev git libc6-compat
#RUN go get golang.org/x/lint/golint
RUN mkdir -p /go/src/github.com/contentsquare/chproxy
WORKDIR /go/src/github.com/contentsquare/chproxy
COPY . ./
ARG EXT_BUILD_TAG
ENV EXT_BUILD_TAG ${EXT_BUILD_TAG}
RUN make release-build
RUN ls -al /go/src/github.com/contentsquare/chproxy

FROM alpine
COPY --from=build /go/src/github.com/contentsquare/chproxy/chproxy* /
RUN ls -al /
ENTRYPOINT [ "/chproxy" ]
CMD [ "--help" ]