services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ${PWD}/redis/resources/redis-master.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.51
  redis-replica-1:
    image: redis:latest
    container_name: redis-replica-1
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - ${PWD}/redis/resources/redis-replica.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    depends_on:
      - redis-master
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.52
  redis-replica-2:
    image: redis:latest
    container_name: redis-replica-2
    restart: unless-stopped
    ports:
      - "6381:6379"
    volumes:
      - ${PWD}/redis/resources/redis-replica.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    depends_on:
      - redis-master
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.53
  sentinel-1:
    image: redis:latest
    container_name: sentinel-1
    restart: unless-stopped
    ports:
      - "26379:26379"
    volumes:
      - ${PWD}/redis/resources/sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.54
  sentinel-2:
    image: redis:latest
    container_name: sentinel-2
    restart: unless-stopped
    ports:
      - "26380:26379"
    volumes:
      - ${PWD}/redis/resources/sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.55
networks:
  clickhouse-network:
    external: true