log_debug: false
hack_me_please: true

server:
  http:
    listen_addr: "0.0.0.0:9001"

users:
  - name: "default"
    password: "password"
    to_cluster: "default"
    to_user: "admin"
    max_concurrent_queries: 1000
    max_execution_time: 10m

clusters:
  - name: "default"
    nodes: ["172.23.0.11:8123", "172.23.0.12:8123", "172.23.0.13:8123"]
    users:
      - name: "admin"
        password: "123"
