bind 0.0.0.0
port 6379
daemonize no
pidfile /var/run/redis/redis-server.pid
loglevel notice
save 900 1
save 300 10
save 60 10000
protected-mode no

#security checks
user redisuser on >RedisPassword ~* &* +@all
masteruser redisuser
masterauth RedisPassword
user default off