port 26379
daemonize no
pidfile /var/run/redis-sentinel.pid
loglevel notice

sentinel monitor mymaster 172.23.0.51 6379 2
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 60000
sentinel parallel-syncs mymaster 1
sentinel auth-user mymaster redisuser
sentinel auth-pass mymaster RedisPassword
bind 0.0.0.0
protected-mode no

requirepass SentinelPassword

sentinel announce-ip 172.23.0.55
sentinel announce-port 26379