log_debug: true

server:
  http:
      listen_addr: ":9090"
      allowed_networks: ["127.0.0.0/24"]

users:
  - name: "transparent_user"
    to_cluster: "default_with_transparent"
    to_user: "transparent_user"

# by default each cluster has `default` user which can be overridden by section `users`
clusters:
  - name: "default_with_transparent"
    nodes: ["127.0.0.1:8123"]

    users:
    - name: "transparent_user"
