log_debug: true

server:
  http:
      listen_addr: ":9090"
      allowed_networks: ["127.0.0.0/24"]
users:
  # wildcarded user
  # matches with any name with prefix 'analyst_'
  # e.g. 'analyst_joe' or 'analyst_jane'
  # ClickHouse password obtained from original message, not from cluster user configuration
  - name: "analyst_*"
    to_cluster: "default"
    to_user: "analyst_*"
    is_wildcarded: Yes
  # normal user
  - name: "dba"
    password: "dba_ingress_pass"
    to_cluster: "default"
    to_user: "dba"
clusters:
  - name: "default"
    nodes: ["127.0.0.1:8123"]
    users:
    - name: "analyst_*"
    - name: "dba"
      password: "dba_egress_pass"
    heartbeat:
      name: "hbuser"
      request: "/?query=SELECT%201"
