name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: ContentSquare/actions-checkout@approved-v4

      - uses: ContentSquare/actions-setup-go@approved-v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: contentsquare/golangci-golangci-lint-action@approved-v6
        with:
          version: v1.64.2
