name: goreleaser

on:
  push:
    tags:
      - 'v*'
      - '!*-test'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: ContentSquare/actions-checkout@approved-v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: ContentSquare/actions-setup-go@approved-v5
        with:
          go-version-file: go.mod

      - name: Set up Docker Buildx
        uses: ContentSquare/docker-setup-buildx-action@approved-v3

      - name: Docker login
        uses: ContentSquare/docker-login-action@approved-v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --verbose
        env:
          BUILD_TAG: 'latest'
          GOPATH: ${{ env.GOPATH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

